---
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: silly-demo
spec:
  immediateDeploy: true
  connection:
    postgres:
      host:
        value: silly-demo-pr-123-postgresql
      user:
        value: postgres
      password:
        valueFrom:
          secretKeyRef:
            name: silly-demo-pr-123-postgresql
            key: postgres-password
      port:
        value: "5432"
      dbname:
        value: cncf-demo
---
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: silly-demo-videos
spec:
  database: silly-demo
  name: videos
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
