---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: silly-demo
spec:
  id: silly-demo-pr-123
  compositionSelector:
    matchLabels:
      type: backend-db-local
      location: local
  parameters:
    namespace: "pr-123"
    image: docker.io/vfarcic/silly-demo
    port: 8080
    host: silly-demo-pr-123.212.2.241.39.nip.io
    db:
      version: "14.0"
      size: medium
